### PR TITLE
Search for the first match of gawk in the $PATH environment variable.

### PR DESCRIPTION
**Pull request by mlsmrc**

### CODE REVIEW

**Comment by kovetskiy** [comment]
Hi, the tests have failed since `env` doesn't pass `-f` to gawk, it tries to find a binary `gawk -f`

It's also easy to reproduce the problem on a Linux host:
```bash
 $ ~/shdoc master↕ ./shdoc -h
/usr/bin/env: ‘gawk -f’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

**Comment by kovetskiy** [comment]
I wonder if we can use something like this:
```
#!/usr/bin/env -S gawk -f -
```

accrording to `map env`
```
       -S, --split-string=S
              process and split S into separate arguments; used to pass multiple arguments on shebang lines
```

**Comment by mlsmrc** [comment]
I see master already contains the requested changes. So maybe I can close this PR :)

**Comment by kovetskiy** [comment]
@mlsmrc you are probably confusing this with #36 since I partially merged it and didn't touch the shebang. 
The master branch doesn't contain the fixed version of shebang: https://github.com/reconquest/shdoc/blob/master/shdoc#L1

**Comment by sanguis** [comment]
can we repoen this as it does fix the issue on mac

**Comment by nmccready** [comment]
Please re-open "this is the way".

**Pull request closed without merging**
