### PR TITLE
Supports OSX and fix example test

### PR DESCRIPTION
**Pull request by yanagiragi**
The PR aim to support and fix:

1. Current script does not support OSX

    Mentioned in #24 , I tried adding `#!/usr/bin/env -S gawk -f`, however the option `-S` only works on BSD distributions. The proper way to handle shebang would been execute shdoc using the way mentoned in [here](https://unix.stackexchange.com/a/97280). However my approach is to simply replace shebang when install in Makefile.

3. Example does not work

   The main reason is that the regex to capture function name does not support hyphen (`-`), which turns out included in the example. So I simply add a `\-` in the regex.
  
  - Latest commit output:
  
  <pre>
  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  ~/Desktop/Ragi/shdoc-original(master*) » ./shdoc examples/readme-example.sh                                                                                                                                    
  zsh: ./shdoc: bad interpreter: /usr/bin/gawk: no such file or directory
  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  ~/Desktop/Ragi/shdoc-original(master*) » sed 's/\/usr\/bin\/gawk/\/usr\/local\/bin\/gawk/' shdoc > new-shdoc # temporarily hack                                                                            127 
  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  ~/Desktop/Ragi/shdoc-original(master*) » chmod u+x new-shdoc                                                                                                                                                   
  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  ~/Desktop/Ragi/shdoc-original(master*) » ./new-shdoc examples/readme-example.sh                                                                                                                                
  # libexample
  
  A library that solves some common problems.
  
  ## Overview
  
  The project solves lots of problems:
  * a
  * b
  * c
  * etc
  </pre>
  
  - Latest commit output from forked project:
  
  <pre>
  ~/Desktop/Ragi/shdoc(master*) » ./new-shdoc examples/readme-example.sh                                                                                                                                           
  # libexample
  
  A library that solves some common problems.
  
  ## Overview
  
  The project solves lots of problems:
  * a
  * b
  * c
  * etc
  
  ## Index
  
  * [say-hello()](#say-hello)
  
  ### say-hello()
  
  My super function.
  Not thread-safe.
  
  #### Example
  
  ```bash
  echo "test: $(say-hello World)"
  ```
  
  #### Arguments
  
  * **$1** (string): A value to print
  
  #### Exit codes
  
  * **0**: If successful.
  * **1**: If an empty string passed.
  
  #### See also
  
  * [validate()](#validate)
  </pre>

### CODE REVIEW

**Comment by yanagiragi** [comment]
I found another issue: The anchor name is mismatched.

```markdown
 ## Index
  
  * [say-hello()](#say-hello) << not match!
  
 ### say-hello()
```

Fixed in 433a0ba41724d89b1dfe9b05a35c4203c00ab913 by remove parentheses in the generated headers

**Comment by kovetskiy** [comment]
Hi, could you please fix the tests? They work correctly, but they expected an incorrect result.

**Comment by yanagiragi** [comment]
@kovetskiy Fixed.

**Comment by kovetskiy** [comment]
Merged, thanks!

**Pull request merged**
