### PR TITLE
Adding OS-X install script + supporting dots

### PR DESCRIPTION
**Pull request by kigster**
* On my system default awk was throwing errors.
 * Installing gawk solved the issue.
 * My function namespaces are separated by a dot, not by colon.
 * So added a dot to the function definition regex.

### CODE REVIEW

**Comment by kovetskiy** [comment]
Hi! 

Thanks for the PR, what if we actually have a brew's tap instead of this script and put this logic into the tap? 

https://docs.brew.sh/Taps

**Comment by kovetskiy** [comment]
Could you also take a look why tests failed?

**Comment by kigster** [comment]
Sure, I’ll take a look

**Comment by kigster** [comment]
Closing this in favor of #23

**Pull request closed without merging**
